name: Dragon CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1 : Installation et build (ne change pas beaucoup)
  install-and-build:
    name: Install & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install all dependencies
        run: |
          npm install --prefix packages/registry
          npm install --prefix packages/cli

  # Job 2 : Tests d'intégration (c'est la nouveauté !)
  integration-tests:
    name: Integration Tests
    # Ce job ne commencera que si 'install-and-build' a réussi
    needs: install-and-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # On réinstalle les dépendances (c'est une nouvelle machine)
      - name: Install all dependencies
        run: |
          npm install --prefix packages/registry
          npm install --prefix packages/cli

      # On installe notre commande 'drn' globalement
      - name: Link CLI for testing
        run: npm link --prefix packages/cli

      # On lance notre serveur API en arrière-plan
      - name: Start Dragon Registry in background
        run: npm start --prefix packages/registry &

      # On attend que le serveur soit prêt avant de continuer
      - name: Wait for Registry to be ready
        run: npx wait-on http://127.0.0.1:3000

      # On lance le test !
      - name: Run CLI ping test
        run: npm test --prefix packages/cli
